REQUESTED = "REQUESTED"
OFFERED = "OFFERED"
DRIVER_ASSIGNED = "DRIVER_ASSIGNED"
DRIVER_EN_ROUTE = "DRIVER_EN_ROUTE"
DRIVER_ARRIVED = "DRIVER_ARRIVED"
PICKUP_PENDING = "PICKUP_PENDING"
IN_PROGRESS = "IN_PROGRESS"
COMPLETED = "COMPLETED"
CANCELED = "CANCELED"

ACTIVE_REQUEST_STATES = {REQUESTED, OFFERED}
ACTIVE_TRIP_STATES = {REQUESTED, OFFERED, DRIVER_ASSIGNED, DRIVER_EN_ROUTE, DRIVER_ARRIVED, PICKUP_PENDING, IN_PROGRESS}
